# Generated by Django 5.1.2 on 2024-11-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customermodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='Image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='customer_phone',
            field=models.CharField(max_length=10),
        ),
    ]
